// 60 affirmations cycling by day-of-year
const AFFIRMATIONS = [
  "Everything you have asked for is already on its way to you.",
  "You are magnetic. The right people, opportunities, and abundance find you effortlessly.",
  "Your dreams are not too big. You are simply growing into them.",
  "Today you move with clarity, confidence, and an open heart.",
  "The life you imagine is not a fantasy — it is a memory waiting to happen.",
  "You are allowed to take up space. You are allowed to have everything you want.",
  "Abundance is your natural state. You return to it now.",
  "You trust the timing of your life completely.",
  "What you focus on expands. Today you focus on what is beautiful.",
  "You are not chasing your dreams — you are walking toward them.",
  "Your mind is a powerful instrument. Today you tune it to possibility.",
  "You deserve the same love you so freely give to others.",
  "Every day you become a clearer, stronger version of yourself.",
  "The universe is conspiring in your favour right now.",
  "You are exactly where you need to be, on your way to where you want to go.",
  "Doors open easily for you. The right ones always do.",
  "You carry a quiet confidence that nothing can shake.",
  "Your future self is already living the life you are writing about today.",
  "You release what no longer serves you and make room for miracles.",
  "Today is full of moments that will become the story you love to tell.",
  "You are worthy of rest, joy, and extraordinary success — all at once.",
  "The version of you who has it all believes in you right now.",
  "You attract what you are. Keep becoming.",
  "Gratitude turns what you have into more than enough.",
  "You are building something that will outlast your doubts.",
  "Your energy is a gift. The world is better because you showed up today.",
  "You are safe to dream boldly.",
  "Good things are not a coincidence in your life — they are a pattern.",
  "You are deeply loved, deeply capable, and deeply enough.",
  "Today's words become tomorrow's reality.",
  "You are not waiting for permission. You already have it.",
  "Everything is always working out for you.",
  "Your presence is your power.",
  "You move through the world with ease and grace.",
  "Clarity is coming. Trust the unfolding.",
  "You have survived every hard day so far — you are undefeated.",
  "Wealth, health, love, and purpose are not mutually exclusive. You claim all four.",
  "You are a work of art in progress — already beautiful, still becoming.",
  "The best ideas find you when you are still and open.",
  "You give yourself full permission to be happy right now.",
  "Your intuition is your superpower. You listen to it today.",
  "You are not behind. You are exactly on time.",
  "Something wonderful is about to happen.",
  "You are the author of your story — and what a story it is becoming.",
  "You radiate warmth and people are drawn to your light.",
  "Every small step is sacred. You honour yours.",
  "You wake up each day with more capacity than the day before.",
  "The life you want wants you back.",
  "You are releasing old stories and writing new, truer ones.",
  "Today you choose yourself — fully, joyfully, unapologetically.",
  "Your greatest chapter has not been written yet.",
  "You are a clear channel for creativity, love, and inspired action.",
  "What feels impossible today will feel inevitable tomorrow.",
  "You are held, guided, and supported — always.",
  "You give yourself grace as freely as you give it to others.",
  "The world needs exactly what only you can offer.",
  "You are not your fear. You are the one who walks through it.",
  "Peace is available to you right now. You choose it.",
  "You are becoming someone even better than you planned.",
  "Today is a good day for something extraordinary to begin.",
]

export function getDailyAffirmation() {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86_400_000
  )
  return AFFIRMATIONS[dayOfYear % AFFIRMATIONS.length]
}
